#!/bin/zsh

_zshrc_log "PATH: $PATH"

pathmunge () {
    if ! echo "$PATH" | egrep -q "(^|:)$1(\$|:)" ; then
	if [ "$2" = "after" ] ; then
            _zshrc_log "Adding $1 to end of PATH"
	    PATH=$PATH:$1
	else
            _zshrc_log "Adding $1 to PATH"
	    PATH=$1:$PATH
	fi
    fi
}

pathremove ()  {
    _zshrc_log "Removing $1 from PATH"
    export PATH=$(echo -n "$PATH" | awk -v RS=: -v ORS=: '$0 != "'"$1"'"' | \
        sed 's/:$//')
}

if [ -e ~/bin ]; then
    pathmunge ~/bin
fi

# these need to go after /usr/bin to make mock work properly
pathmunge /sbin after
pathmunge /usr/sbin after

[ -e "$HOME"/.zsh.d/path.local ] && source "$HOME"/.zsh.d/path.local

export PATH
