#!/bin/zsh

alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias .=source

if type alpine >& /dev/null; then
    alias pine='alpine -i'
fi

if type greadlink >& /dev/null; then
    alias readlink=greadlink
fi

if type gstat >& /dev/null; then
    alias stat=gstat
fi

[ -e $HOME/.zsh.d/aliases.local ] && source $HOME/.zsh.d/aliases.local

function socks() {
    # todo: make port configurable
    ssh -D 8000 -fCqN "$@" && echo "proxy started on port 8000"
}
