#!/bin/zsh

__AUTORELOAD_LAST_RUN=$(date +%s)

# automatically reload .zshrc when necessary.
autoreload() {
    # only run this once an hour at most
    if (( $(($(date +%s) - $__AUTORELOAD_LAST_RUN)) > 3600 )); then
        if (( $(stat -c %Y ~/.zshrc) > $__AUTORELOAD_LAST_RUN )); then
            # .zshrc sources all of the .zsh.d files, so we just
            # source it and let it do the heavy lifting
            echo "autoreload ~/.zshrc"
            source ~/.zshrc
        else
            touch -d @$__AUTORELOAD_LAST_RUN ~/.zsh.d/.autoreload
            for zshrc_snipplet in $(find ~/.zsh.d -name 'S[0-9][0-9]*' \
                                    -newer ~/.zsh.d/.autoreload); do
                echo "autoreload $zshrc_snipplet"
                source $zshrc_snipplet
            done
            rm -f ~/.zsh.d/.autoreload
        fi

        __AUTORELOAD_LAST_RUN=$(date +%s)
    fi
}

preexec_functions[$(($#preexec_functions + 1))]='autoreload'
