#!/bin/zsh

pathmunge () {
    if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
	if [ "$2" = "after" ] ; then
	    PATH=$PATH:$1
	else
	    PATH=$1:$PATH
	fi
    fi
}

if [ -e ~/bin ]; then
    pathmunge ~/bin
fi
if [ -e ~/sw/$(uname -s)-$(uname -r | cut -d. -f 1,2)-$(uname -m) ]; then
    pathmunge ~/sw/$(uname -s)-$(uname -r | cut -d. -f 1,2)-$(uname -m)
fi

# these need to go after /usr/bin to make mock work properly
pathmunge /sbin after
pathmunge /usr/sbin after

[ -e $HOME/.zsh.d/path.local ] && source $HOME/.zsh.d/path.local

export PATH
