#!/bin/zsh

pathmunge () {
    if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
	if [ "$2" = "after" ] ; then
	    PATH=$PATH:$1
	else
	    PATH=$1:$PATH
	fi
    fi
}

if [ -e ~/bin ]; then
    pathmunge ~/bin
fi
if [ -e ~/nfs/bin ]; then
    pathmunge ~/nfs/bin after
fi

# these need to go after /usr/bin to make mock work properly
pathmunge /sbin after
pathmunge /usr/sbin after

[ -e path.local ] && source path.local

export PATH
