#!/bin/zsh

alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias .=source

if type alpine >& /dev/null; then
    alias pine='alpine -i'
fi

[ -e $HOME/.zsh.d/aliases.local ] && source $HOME/.zsh.d/aliases.local
