#!/bin/zsh

export __CURRENT_GIT_REPO=
export __CURRENT_GIT_BRANCH=
export __CURRENT_GIT_UNPUSHED=

_parse_git_repo() {
    export __CURRENT_GIT_REPO="$(git remote -v 2> /dev/null | \
        awk '/^origin[[:space:]].*\(fetch\)$/ {
                 split($2,a,"[:/]");
                 sub(/\.git$/, "", a[length(a)]);
                 print a[length(a)]; }' | \
        tail -n 1)"
    if [[ -n $__CURRENT_GIT_REPO && $__CURRENT_GIT_REPO != "dotfiles" ]]; then
        export __CURRENT_GIT_BRANCH="$(git what-branch)"
        local _unpushed="$(git log @{u}.. --oneline 2>&1)"
        if [[ -n $_unpushed ]] && ! echo "$_unpushed" | grep -q fatal; then
            export __CURRENT_GIT_UNPUSHED="$(echo $_unpushed | wc -l | tr -d ' ')"
        else
            export __CURRENT_GIT_UNPUSHED=
        fi
    else
        export __CURRENT_GIT_BRANCH=
        export __CURRENT_GIT_UNPUSHED=
    fi
}

_zsh_update_git_vars() {
    case "$1" in
        *git*)
            parse_git_repo
            ;;
        g\ *)
            parse_git_repo
            ;;
    esac
}

_get_git_prompt_info() {
    if [[ -n $__CURRENT_GIT_REPO && -n $__CURRENT_GIT_BRANCH ]]; then
        if [[ $__CURRENT_GIT_UNPUSHED > 0 ]]; then
            echo "${PR_CYAN}${__CURRENT_GIT_REPO}:${__CURRENT_GIT_BRANCH} ${PR_BRIGHT_CYAN}(${__CURRENT_GIT_UNPUSHED})${PR_RESET}"
        else
            echo "${PR_CYAN}${__CURRENT_GIT_REPO}:${__CURRENT_GIT_BRANCH}${PR_RESET}"
        fi
    fi
}

if type git >& /dev/null; then
    if [[ $(type git) == "git is a shell function" ]]; then
        unfunction git
    fi

    # we run parse_git_repo and parse_git_branch on three occasions:
    #
    # 1.  When this file is first loaded;
    # 2.  When a git command is run; and
    # 3.  When cd is run
    _parse_git_repo
    add-zsh-hook preexec _zsh_update_git_vars
    add-zsh-hook chpwd _parse_git_repo

    if type hub >& /dev/null; then
        eval "$(hub alias -s)"
    fi
fi

alias g=git
alias gg='git grep'
alias grim='git rebase -i master'
alias grp='git rebase-push'
alias gs='git status'
alias gu='git up'
