#!/bin/zsh

export __CURRENT_SVN_REPO=

_parse_svn_repo() {
    export __CURRENT_SVN_REPO="$(svn info 2> /dev/null | \
        awk -F '[[:space:]]+|/' '/Repository Root/ {print $NF}')"
}

_zsh_preexec_update_svn_vars() {
    case "$(history -1)" in
        *svn*)
            parse_svn_repo
            ;;
    esac
}

if type svn >& /dev/null; then
    # we run parse_svn_repo on three occasions:
    #
    # 1.  When this file is first loaded;
    # 2.  When an svn command is run; and
    # 3.  When cd is run
    _parse_svn_repo
    add-zsh-hook preexec _zsh_preexec_update_svn_vars
    add-zsh-hook chpwd _parse_svn_repo
fi

get_svn_prompt_info() {
    if [[ -n $__CURRENT_SVN_REPO ]]; then
        echo "${PR_CYAN}$__CURRENT_SVN_REPO${PR_RESET}"
    fi
}
