#!/bin/zsh

SSH_AGENT_FILE=$(readlink -f ~/.ssh-agent-info)

start-ssh-agent() {
    rv=0
    if type ssh-agent >& /dev/null; then
        if [[ -e $SSH_AGENT_FILE ]]; then
            source "$SSH_AGENT_FILE"
            proc=$(ps -p "$SSH_AGENT_PID" -o comm=)
            if [[ $proc != "ssh-agent" ]]; then
                export SSH_AUTH_SOCK=
                export SSH_AGENT_PID=
                rm -f "$SSH_AGENT_FILE"
            else
                return $rv
            fi
        fi
        cmds=$(ssh-agent | grep -v '^echo')
        rv=$((rv + $?))
        eval $cmds
        rv=$((rv + $?))
        echo "$cmds" >| "$SSH_AGENT_FILE"
    fi
    return $rv
}

start-ssh-agent

# I used to have a command called scp_via, but it was obsoleted by 'scp -3'
alias scp_via 'scp -3'
