#!/bin/zsh

# https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client
# this is just for mac os; would be nice to have it for linux too
_OP_AGENT_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

if [[ -e "$_OP_AGENT_SOCK" ]]; then
    export SSH_AUTH_SOCK="$_OP_AGENT_SOCK"
else
    SSH_AGENT_FILE=$(readlink -f ~/.ssh-agent-info)

    start-ssh-agent() {
        rv=0
        if type ssh-agent >& /dev/null; then
            if [[ -e $SSH_AGENT_FILE ]]; then
                source "$SSH_AGENT_FILE"
                proc=$(ps -p "$SSH_AGENT_PID" -o comm=)
                if [[ $proc != "ssh-agent" ]]; then
                    export SSH_AUTH_SOCK=
                    export SSH_AGENT_PID=
                    rm -f "$SSH_AGENT_FILE"
                else
                    return $rv
                fi
            fi
            cmds=$(ssh-agent | grep -v '^echo')
            rv=$((rv + $?))
            eval $cmds
            rv=$((rv + $?))
            echo "$cmds" >| "$SSH_AGENT_FILE"
        fi
        return $rv
    }

    start-ssh-agent
fi

# I used to have a command called scp_via, but it was obsoleted by 'scp -3'
alias scp_via 'scp -3'
