#!/bin/zsh

if type emacs >& /dev/null; then
    version=$(emacs --version | head -n 1 | \
        awk '{ split($NF, v, "."); print v[1] "." v[2]; }')
    if type emacsclient >& /dev/null && [[ $version -ge 23.1 ]]; then
        # start emacs server
        if ! pgrep -f 'emacs --daemon' >& /dev/null; then
            \emacs --daemon >& /dev/null
        fi

        export ALTERNATIVE_EDITOR=""
        if [[ -n $DISPLAY ]]; then
            alias emacs="emacsclient -c"
            alias vi="emacsclient -t"
        else
            alias emacs="emacsclient -t"
            alias vi=emacs
        fi
    fi
    export EDITOR=emacs
    alias emcas=emacs
elif type vim >& /dev/null; then
    export EDITOR=vim
    alias vi=vim
    alias emacs=vim
else
    export EDITOR=vi
    alias emacs=vi
fi

