#!/bin/zsh

function __start_emacs_server() {
    # start emacs server
    if ! pgrep -f 'emacs --daemon' >& /dev/null; then
        $__emacs_bin --daemon -q >& /dev/null
    fi
}

if type emacs >& /dev/null; then
    if [[ -z $__emacs_bin ]]; then
        if [[ $(type emacs) == "emacs is a shell function" ]]; then
            unfunction emacs
        fi
        __emacs_bin=$(which emacs)
    fi
    __emacs_version=$($__emacs_bin --version | head -n 1 | \
        awk '{ split($NF, v, "."); print v[1] "." v[2]; }')

    if type emacsclient >& /dev/null && [[ $__emacs_version -ge 23.1 ]]; then
        function emacs() {
            __start_emacs_server
            if [[ -n $DISPLAY ]]; then
                args="-c $@"
            else
                args="-t $@"
            fi
            emacsclient ${=args}
        }

        function emacs-kill() {
            emacsclient -e '(kill-emacs)'
        }

        __start_emacs_server
        export ALTERNATIVE_EDITOR=""
    fi
    export EDITOR=emacs
elif type vim >& /dev/null; then
    export EDITOR=vim
else
    export EDITOR=vi
fi

alias emcas=$EDITOR
alias vi=$EDITOR
