#!/bin/zsh

export PIP_DOWNLOAD_CACHE=~/.pip_downloads

if [[ ! -e "$HOME"/.pyenv ]]; then
    echo "Installing pyenv"
    curl https://pyenv.run | bash
fi

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

clean_pyc() {
    if [[ -z $1 ]]; then
        dir=$(pwd)
    else
        dir=$1
    fi
    find "$dir" -name __pycache__ -o -name .mypy_cache -o -regex '.+\.py[co]$' \
         -delete
}

if [[ -e $HOME/.poetry/env ]]; then
    source $HOME/.poetry/env
fi
