#!/bin/zsh

if [[ -e ~/Library/Caches ]]; then
    export PIP_DOWNLOAD_CACHE=~/Library/Caches/pip_downloads
else
    export PIP_DOWNLOAD_CACHE=~/.pip_downloads
fi

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

clean_pyc() {
    if [[ -z $1 ]]; then
        dir=$(pwd)
    else
        dir=$1
    fi
    find "$dir" -name __pycache__ -o -name .mypy_cache -o -regex '.+\.py[co]$' \
         -delete
}

if [[ -e $HOME/.poetry/env ]]; then
    source $HOME/.poetry/env
fi
