#!/bin/zsh

export WORKON_HOME=~/venv
export PROJECT_HOME=~/devel
export VIRTUALENVWRAPPER_HOOK_DIR="$WORKON_HOME"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export NODE_VIRTUAL_ENV_DISABLE_PROMPT=1

# find virtualenvwrapper in $PATH
#source "$(which virtualenvwrapper.sh)"

get_venv_prompt_info() {
    if [[ -n $VIRTUAL_ENV ]]; then
        echo "${PR_GREEN}$(basename "$VIRTUAL_ENV")${PR_RESET}"
    fi
}

venv_install_node_js() {
    if [[ -z $VIRTUAL_ENV ]]; then
        echo "This command must be run inside an active virtual environment"
        exit 1
    fi
    pip install nodeenv
    nodeenv -p
    proj=$VIRTUAL_ENV
    deactivate
    workon "$proj"
}
