#!/usr/bin/env zsh

if [[ -e "$HOME/go" ]]; then
  export GOPATH=$HOME/go
  pathmunge "$GOPATH"/bin
fi

_go_version=

_get_go_version() {
    local gpath=${1:-$(pwd)}
    if [[ -e "$gpath"/go.mod ]]; then
        _go_version=$(go list -m -f '{{.GoVersion}}' | head -n 1)
        return
    elif [[ -e "$gpath"/.git || "$gpath" == "/" ]]; then
        _go_version=
        return
    else
        _get_go_version "$(dirname "$gpath")"
    fi
}

_get_go_prompt_info() {
    if [[ -n "$_go_version" ]]; then
        echo -n "go$_go_version"
    fi
}

if type go >& /dev/null; then
    add_prompt_hook _get_go_prompt_info
    add-zsh-hook chpwd _get_go_version
fi
