#!/usr/bin/zsh

if [[ -e ~/devel/pulp/src ]]; then
    # pulp v1
    pathmunge ~/devel/pulp/bin
    export PYTHONPATH=$PYTHONPATH:~/devel/pulp/src
elif [[ -e ~/devel/pulp/platform ]]; then
    # pulp v2
    pathmunge ~/devel/pulp/platform/bin
    export PYTHONPATH=$PYTHONPATH:~/devel/pulp/platform/src
fi
