#!/bin/zsh

_AWS_CREDS=$HOME/.aws

_get_aws_envs() {
    find "$_AWS_CREDS" -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
}

_get_aws_default_env() {
    if [[ -e "$_AWS_CREDS" && -L "$_AWS_CREDS"/default ]]; then
        basename "$(readlink -f "$_AWS_CREDS"/default)"
    fi
}

_get_aws_current_env() {
    if [[ -e "$_AWS_CREDS" && -L "$_AWS_CREDS"/current ]]; then
        basename "$(readlink -f "$_AWS_CREDS"/current)"
    fi
}

aws_env() {
    if [[ -z $1 ]]; then
        echo "Available AWS environments:"
        _get_aws_envs | \
            sed "s/^\(.*\)\$/  \1/;
                 s/^  \($(_get_aws_current_env)\)\$/* \1/;
                 s/^\(..$(_get_aws_default_env)\)\$/\1 (default)/"
    elif [[ -e "$_AWS_CREDS/$1/credentials" ]]; then
        rm -f "$_AWS_CREDS"/current
        ln -s "$_AWS_CREDS/$1" "$_AWS_CREDS"/current
        for filename in config credentials; do
            if [[ ! -e "$_AWS_CREDS/$filename" ]]; then
                ln -s "$_AWS_CREDS/current/$filename" "$_AWS_CREDS/$filename"
            fi
        done
    else
        echo "AWS environment $1 not found"
        aws_env
    fi
}

if [[ -e "$_AWS_CREDS" ]]; then
    if [[ -z _get_aws_current_env && -n _get_aws_default_env ]]; then
        aws_env "$(_get_aws_default_env)"
    fi
fi
