#!/bin/zsh

setopt prompt_subst

_get_prompt() {
    local time="${PR_BRIGHT_YELLOW}%T${PR_RESET} "

    local venv="$(get_venv_prompt_info)"
    local git_info="$(get_git_prompt_info)"
    local svn_info="$(get_svn_prompt_info)"

    if [[ -n $venv && ( -n $git_info || -n $svn_info ) ]]; then
        local cwd="%${PR_PWDLEN}<...<%~%<<"
        local user="%(!#${PR_SEP}${PR_BRIGHT_RED}%n${PR_RESET}#)"
        echo "${venv}${PR_SEP}${cwd}${PR_SEP}${git_info}${svn_info}
${time}${user}"
    else
        local cwd="%~"
        local user="%(!#${PR_BRIGHT_RED}%n${PR_RESET}${PR_SEP}#)"
        prompt=${time}${user}${cwd}
        if [[ -n $venv ]]; then
            prompt=$prompt$PR_SEP$venv
        fi
        if [[ -n $git_info || -n $svn_info ]]; then
            prompt=$prompt$PR_SEP$git_info$svn_info
        fi
        echo "$prompt"
    fi
}

# lprompt() {
#     local time="${PR_BRIGHT_YELLOW}%T${PR_RESET} "
#     local user="%(!#${PR_SEP}${PR_BRIGHT_RED}%n${PR_RESET}#)"
#     local venv='$(get_venv_prompt_info)'
#     local cwd="%~"
#     local retval="%(?##${PR_RED}[%?]${PR_RESET})"
#     local git_info='$(get_git_prompt_info)'
#     local svn_info='$(get_svn_prompt_info)'

#     export PROMPT="${venv}${cwd}${git_info}${svn_info}
# ${time}${user}${retval}%# "
# }

lprompt() {
    local retval="%(?##${PR_RED}[%?]${PR_RESET})"
    export PROMPT='$(_get_prompt)'"${retval}%# "
}

rprompt() {
    local machine="${PR_BRIGHT_BLUE}["'$__CURRENT_HOSTNAME'"]${PR_RESET}"

    # if we're inside screen, then the hostname will be in the status
    # bar and we don't need it in the prompt, too
    if [[ $TERM[0,6] == "screen" || $TERM[0,5] == "eterm" ]]; then
        RPROMPT=""
    else
        RPROMPT="${machine}"
    fi
    export RPROMPT
}

get_pwd_length() {
    local prompt="$(get_venv_prompt_info)$(get_git_prompt_info)$(get_svn_prompt_info)"
    local zero='%([BSUbfksu]|([FB]|){*})'
    promptlength=${#${(S%%)prompt//$~zero/}}
    PR_PWDLEN=$((COLUMNS - promptlength))
}

lprompt
rprompt
get_pwd_length

preexec_functions[$(($#preexec_functions + 1))]='get_pwd_length'
