#!/bin/zsh

setopt prompt_subst

lprompt() {
    local time="${PR_BRIGHT_YELLOW}%T${PR_RESET} "
    local user="%(!#${PR_RESET}${PR_BRIGHT_RED}%n${PR_RESET}:#)"
    local venv="${PR_GREEN}"'$(get_venv_prompt_info)'"${PR_RESET}"
    local cwd="%~"
    local retval="%(?##${PR_RED}[%?]${PR_RESET})"
    local git_info="${PR_CYAN}"'$(get_git_prompt_info)'"${PR_RESET}"
    local svn_info="${PR_CYAN}"'$(get_svn_prompt_info)'"${PR_RESET}"

    export PROMPT="${time}${user}${venv}${cwd}${git_info}${svn_info}${retval}%# "
}

rprompt() {
    local machine="${PR_BRIGHT_BLUE}["'$__CURRENT_HOSTNAME'"]${PR_RESET}"

    # if we're inside screen, then the hostname will be in the status
    # bar and we don't need it in the prompt, too
    if [[ $TERM[0,6] == "screen" || $TERM[0,5] == "eterm" ]]; then
        RPROMPT=""
    else
        RPROMPT="${machine}"
    fi
    export RPROMPT
}

lprompt
rprompt
