#!/bin/zsh

# tab-complete hosts in .ssh/known_hosts
local _myhosts
_myhosts=( ${${${${(f)"$(<$HOME/.ssh/known_hosts)"}:#[0-9]*}%%\ *}%%,*} )
zstyle ':completion:*' hosts $_myhosts

# fun snowflake effect.  'tis the season and all that
function snow() {
    clear
    while :; do
        LINES=$(tput lines)
        COLUMNS=$(tput cols)
        echo $LINES $COLUMNS $(($RANDOM%$COLUMNS))
        sleep 0.1
    done | gawk '{
                  a[$3]=0;
                  for (x in a) {
                      o=a[x];
                      a[x]=a[x]+1;
                      printf "\033[%s;%sH ",o,x;
                      printf "\033[%s;%sH*\033[0;0H",a[x],x;
                  }
                 }'
}
