;;; Quickstart file to activate all packages at startup  -*- lexical-binding:t -*-
;; ¡¡ This file is autogenerated by `package-quickstart-refresh', DO NOT EDIT !!

(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/ws-butler-20250310.205/ws-butler-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'ws-butler-mode "ws-butler" "\
Whitespace cleanup without obtrusive whitespace removal.

Whitespaces at end-of-line and end-of-buffer are trimmed upon save, but
only for lines modified by you.

This is a minor mode.  If called interactively, toggle the `Ws-Butler
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `ws-butler-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'ws-butler-global-mode 'globalized-minor-mode t)
(defvar ws-butler-global-mode nil "\
Non-nil if Ws-Butler-Global mode is enabled.
See the `ws-butler-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ws-butler-global-mode'.")
(custom-autoload 'ws-butler-global-mode "ws-butler" nil)
(autoload 'ws-butler-global-mode "ws-butler" "\
Toggle Ws-Butler mode in all buffers.
With prefix ARG, enable Ws-Butler-Global mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Ws-Butler mode is enabled in all buffers where `ws-butler--global-mode-turn-on'
would do it.

See `ws-butler-mode' for more information on Ws-Butler mode.

(fn &optional ARG)" t)
(register-definition-prefixes "ws-butler" '("ws-butler-"))


(provide 'ws-butler-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/treesit-auto-20260831.1012/treesit-auto-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(register-definition-prefixes "treesit-auto" '("global-treesit-auto-mode" "treesit-auto-"))


(provide 'treesit-auto-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/hcl-mode-20240220.1534/hcl-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'hcl-mode "hcl-mode" "\
Major mode for editing hcl configuration file

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.hcl\\'" . hcl-mode))
(add-to-list 'auto-mode-alist '("\\.nomad\\'" . hcl-mode))
(register-definition-prefixes "hcl-mode" '("hcl-"))


(provide 'hcl-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/dash-20250312.1307/dash-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'dash-fontify-mode "dash" "\
Toggle fontification of Dash special variables.

Dash-Fontify mode is a buffer-local minor mode intended for Emacs
Lisp buffers.  Enabling it causes the special variables bound in
anaphoric Dash macros to be fontified.  These anaphoras include
`it', `it-index', `acc', and `other'.  In older Emacs versions
which do not dynamically detect macros, Dash-Fontify mode
additionally fontifies Dash macro calls.

See also `dash-fontify-mode-lighter' and
`global-dash-fontify-mode'.

This is a minor mode.  If called interactively, toggle the `Dash-Fontify
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `dash-fontify-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-dash-fontify-mode 'globalized-minor-mode t)
(defvar global-dash-fontify-mode nil "\
Non-nil if Global Dash-Fontify mode is enabled.
See the `global-dash-fontify-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-dash-fontify-mode'.")
(custom-autoload 'global-dash-fontify-mode "dash" nil)
(autoload 'global-dash-fontify-mode "dash" "\
Toggle Dash-Fontify mode in all buffers.
With prefix ARG, enable Global Dash-Fontify mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Dash-Fontify mode is enabled in all buffers where
`dash--turn-on-fontify-mode' would do it.

See `dash-fontify-mode' for more information on Dash-Fontify mode.

(fn &optional ARG)" t)
(autoload 'dash-register-info-lookup "dash" "\
Register the Dash Info manual with `info-lookup-symbol'.
This allows Dash symbols to be looked up with \\[info-lookup-symbol]." t)
(register-definition-prefixes "dash" '("!cdr" "!cons" "--" "->" "-a" "-butlast" "-c" "-d" "-e" "-f" "-gr" "-i" "-juxt" "-keep" "-l" "-m" "-no" "-o" "-p" "-r" "-s" "-t" "-u" "-value-to-list" "-when-let" "-zip" "dash-"))


(provide 'dash-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/terraform-mode-20250528.1335/terraform-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'terraform-mode "terraform-mode" "\
Major mode for editing terraform configuration file

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.t\\(f\\(vars\\)?\\|ofu\\)\\'" . terraform-mode))
(register-definition-prefixes "terraform-mode" '("terraform-"))


(provide 'terraform-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/reformatter-20241204.1051/reformatter-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'reformatter-define "reformatter" "\
Define a reformatter command with NAME.

When called, the reformatter will use PROGRAM and any ARGS to
reformat the current buffer.  The contents of the buffer will be
passed as standard input to the reformatter, which should output
them to standard output.  A nonzero exit code will be reported as
failure, and the output of the command to standard error will be
displayed to the user.

The macro accepts the following keyword arguments:

PROGRAM (required)

  Provides a form which should evaluate to a string at runtime,
  e.g. a literal string, or the name of a variable which holds
  the program path.

ARGS

  Command-line arguments for the program.  If provided, this is a
  form which evaluates to a list of strings at runtime.  Default
  is the empty list.  This form is evaluated at runtime so that
  you can use buffer-local variables to influence the args passed
  to the reformatter program: the variable `input-file' will be
  lexically bound to the path of a file containing the text to be
  reformatted: see the keyword options INPUT-FILE, STDIN and
  STDOUT for more information.

STDIN

  When non-nil (the default), the program is passed the input
  data on stdin.  Set this to nil when your reformatter can only
  operate on files in place.  In such a case, your ARGS should
  include a reference to the `input-file' variable, which will be
  bound to an input path when evaluated.

STDOUT

  When non-nil (the default), the program is expected to write
  the reformatted text to stdout.  Set this to nil if your
  reformatter can only operate on files in place, in which case
  the contents of the temporary input file will be used as the
  replacement text.

INPUT-FILE

  Sometimes your reformatter program might expect files to be in
  a certain directory or have a certain file extension.  This option
  lets you handle that.

  If provided, it is a form which will be evaluated before each
  run of the formatter, and is expected to return a temporary
  file path suitable for holding the region to be reformatted.
  It must not produce the same path as the current buffer's file
  if that is set: you shouldn't be operating directly on the
  buffer's backing file.  The temporary input file will be
  deleted automatically.  You might find the functions
  `reformatter-temp-file-in-current-directory' and
  `reformatter-temp-file' helpful.

MODE

  Unless nil, also generate a minor mode that will call the
  reformatter command from `before-save-hook' when enabled.
  Default is t.

GROUP

  If provided, this is the custom group used for any generated
  modes or custom variables.  Don't forget to declare this group
  using a `defgroup' form.

LIGHTER

  If provided, this is a mode lighter string which will be used
  for the \"-on-save\" minor mode.  It should have a leading
  space.  The supplied value will be used as the default for a
  generated custom variable which specifies the mode lighter.
  Default is nil, ie. no lighter.

KEYMAP

  If provided, this is the symbol name of the \"-on-save\" mode's
  keymap, which you must declare yourself.  Default is no keymap.

EXIT-CODE-SUCCESS-P

  If provided, this is a function object callable with `funcall'
  which accepts an integer process exit code, and returns non-nil
  if that exit code is considered successful.  This could be a
  lambda, quoted symbol or sharp-quoted symbol.  If not supplied,
  the code is considered successful if it is `zerop'.

WORKING-DIRECTORY

  Directory where your reformatter program is started. If provided, this
  should be a form that evaluates to a string at runtime. Default is the
  value of `default-directory' in the buffer.

INTERACTIVE-MODES

  If provided, this is a list of mode names (as unquoted
  symbols).  The created commands for formatting regions and
  buffers are then tagged for interactive use in these modes,
  making them compatible with some built-in predicate functions
  for `read-extended-command-predicate', like
  `command-completion-default-include-p'.

(fn NAME &key PROGRAM ARGS (MODE t) (STDIN t) (STDOUT t) INPUT-FILE LIGHTER KEYMAP GROUP (EXIT-CODE-SUCCESS-P \\='zerop) WORKING-DIRECTORY INTERACTIVE-MODES)" nil t)
(function-put 'reformatter-define 'lisp-indent-function 'defun)
(register-definition-prefixes "reformatter" '("reformatter-"))


(provide 'reformatter-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/sqlformat-20240325.1006/sqlformat-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




 (autoload 'sqlformat-buffer "sqlformat" nil t)
 (autoload 'sqlformat-region "sqlformat" nil t)
 (autoload 'sqlformat-on-save-mode "sqlformat" nil t)
(autoload 'sqlformat "sqlformat" "\
Reformat SQL in region from BEG to END using `sqlformat-region'.
If no region is active, the current statement (paragraph) is reformatted.
Install the \"sqlparse\" (Python) package to get \"sqlformat\", or
\"pgformatter\" to get \"pg_format\", or install the \"sqlfluff\" (Python) 
package to get \"sqlfluff\".

(fn BEG END)" t)
(register-definition-prefixes "sqlformat" '("sqlformat-"))


(provide 'sqlformat-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/solarized-theme-20250913.451/solarized-theme-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'solarized-color-blend "solarized" "\
Blends COLOR1 onto COLOR2 with ALPHA.

COLOR1 and COLOR2 should be color names (e.g. \"white\") or RGB
triplet strings (e.g. \"#ff12ec\").

Alpha should be a float between 0 and 1.

Optional argument DIGITS-PER-COMPONENT can be either 4 (the default) or 2;
use the latter if you need a 24-bit specification of a color.

(fn COLOR1 COLOR2 ALPHA &optional DIGITS-PER-COMPONENT)")
(autoload 'solarized-create-color-palette "solarized" "\
Create color-palette from CORE-PALETTE.

The Returned color-palette has the same format as `solarized-color-palette'

(fn CORE-PALETTE)")
(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "solarized" '("solarized-"))



(register-definition-prefixes "solarized-dark-high-contrast-theme" '("solarized-dark-high-contrast"))



(register-definition-prefixes "solarized-dark-theme" '("solarized-dark"))



(register-definition-prefixes "solarized-faces" '("solarized-definition"))



(register-definition-prefixes "solarized-gruvbox-dark-theme" '("solarized-gruvbox-dark"))



(register-definition-prefixes "solarized-gruvbox-light-theme" '("solarized-gruvbox-light"))



(register-definition-prefixes "solarized-light-high-contrast-theme" '("solarized-light-high-contrast"))



(register-definition-prefixes "solarized-light-theme" '("solarized-light"))



(register-definition-prefixes "solarized-palettes" '("solarized-"))



(register-definition-prefixes "solarized-selenized-black-theme" '("solarized-selenized-black"))



(register-definition-prefixes "solarized-selenized-dark-theme" '("solarized-selenized-dark"))



(register-definition-prefixes "solarized-selenized-light-theme" '("solarized-selenized-light"))



(register-definition-prefixes "solarized-selenized-white-theme" '("solarized-selenized-white"))



(register-definition-prefixes "solarized-theme-utils" '("solarized-import-faces"))



(register-definition-prefixes "solarized-wombat-dark-theme" '("solarized-wombat-dark"))



(register-definition-prefixes "solarized-zenburn-theme" '("solarized-zenburn"))


(provide 'solarized-theme-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/scratch-20220319.1705/scratch-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(defvar scratch-buffer nil "\
Non-nil if the current buffer is a scratch buffer.")
(autoload 'scratch "scratch" "\
Get a scratch buffer for the MODE.

When called interactively with a prefix arg, prompt for the mode.

(fn MODE)" t)
(register-definition-prefixes "scratch" '("scratch-"))


(provide 'scratch-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/s-20220902.1511/s-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(register-definition-prefixes "s" '("s-"))


(provide 's-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/protobuf-mode-20240823.1417/protobuf-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




 (add-to-list 'auto-mode-alist '("\\.proto\\'" . protobuf-mode))
(autoload 'protobuf-mode "protobuf-mode" "\
Major mode for editing Protocol Buffers description language.

The hook `c-mode-common-hook' is run with no argument at mode
initialization, then `protobuf-mode-hook'.

Key bindings:
\\{protobuf-mode-map}

(fn)" t)
(register-definition-prefixes "protobuf-mode" '("protobuf-"))


(provide 'protobuf-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/popup-20250101.843/popup-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(register-definition-prefixes "popup" '("popup-"))


(provide 'popup-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/popon-0.13/popon-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'poponp "popon" "\
Return t if OBJECT is a popon.

(fn OBJECT)")
(autoload 'popon-live-p "popon" "\
Return t if OBJECT is a popon and not killed.

(fn OBJECT)")
(autoload 'popon-get "popon" "\
Get the PROP property of popon POPON.

(fn POPON PROP)")
(autoload 'popon-put "popon" "\
Set the PROP property of popon POPON to VALUE.

(fn POPON PROP VALUE)")
(autoload 'popon-properties "popon" "\
Return a copy the property list of popon POPON.

(fn POPON)")
(autoload 'popon-position "popon" "\
Return the position of popon POPON as a cons (X, Y).

When popon POPON is killed, return nil.

(fn POPON)")
(autoload 'popon-size "popon" "\
Return the size of popon POPON as a cons (WIDTH . HEIGHT).

When popon POPON is killed, return nil.

(fn POPON)")
(autoload 'popon-window "popon" "\
Return the window popon POPON belongs to.

Return nil if popon POPON is killed.

(fn POPON)")
(autoload 'popon-buffer "popon" "\
Return the buffer popon POPON belongs to.

Return nil if popon POPON is killed.

(fn POPON)")
(autoload 'popon-text "popon" "\
Return the text popon POPON is displaying.

POPON may be a killed popon.  Return nil if POPON isn't a popon at
all.

(fn POPON)")
(autoload 'popon-create "popon" "\
Create a popon showing TEXT at POS of WINDOW.

Display popon only if WINDOW is displaying BUFFER.

POS is a cons (X, Y), where X is column and Y is line in WINDOW.  TEXT
should be a string or a cons cell of form (STR . WIDTH).  When TEXT is
a string, each line of it should be of same length (i.e `string-width'
should return the same length for every line).  When TEXT is a cons
cell, STR is used as the text to display and each line of it should be
of visual length width.

PRIORITY is a number (integer or float) between -100 and 100.  Popons
with larger priority values are rendered first.

(fn TEXT POS &optional WINDOW BUFFER PRIORITY)")
(autoload 'popon-kill "popon" "\
Kill popon POPON.

Do nothing if POPON isn't a live popon.  Return nil.

(fn POPON)")
(autoload 'popon-redisplay "popon" "\
Redisplay popon overlays.")
(autoload 'popon-update "popon" "\
Update popons if needed.")
(autoload 'popon-x-y-at-posn "popon" "\
Return the (X, Y) coodinate at position POSN as a cons.

Return nil if a popon can't be shown at position POSN.

NOTE: This uses `posn-at-point', which is slow.  So try to minimize
calls to this function.

(fn POSN)")
(autoload 'popon-x-y-at-pos "popon" "\
Return the (X, Y) coodinate of POINT in selected window as a cons.

Return nil if POINT is not in visible text area.

NOTE: This uses `posn-at-point', which is slow.  So try to minimize
calls to this function.

(fn POINT)")
(autoload 'popon-kill-all "popon" "\
Kill all popons." t)
(register-definition-prefixes "popon" '("popon-"))


(provide 'popon-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/markdown-mode-20250812.423/markdown-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'markdown-mode "markdown-mode" "\
Major mode for editing Markdown files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.\\(?:md\\|markdown\\|mkd\\|mdown\\|mkdn\\|mdwn\\)\\'" . markdown-mode))
(autoload 'gfm-mode "markdown-mode" "\
Major mode for editing GitHub Flavored Markdown files.

(fn)" t)
(autoload 'markdown-view-mode "markdown-mode" "\
Major mode for viewing Markdown content.

(fn)" t)
(autoload 'gfm-view-mode "markdown-mode" "\
Major mode for viewing GitHub Flavored Markdown content.

(fn)" t)
(autoload 'markdown-live-preview-mode "markdown-mode" "\
Toggle native previewing on save for a specific markdown file.

This is a minor mode.  If called interactively, toggle the
`Markdown-Live-Preview mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `markdown-live-preview-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "markdown-mode" '("defun-markdown-" "gfm-" "markdown"))


(provide 'markdown-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/legalese-20200119.2248/legalese-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'legalese "legalese" "\
Add standard legalese prelude to the current buffer.

With prefix-argument ASK, ask for a license to use.

(fn ASK)" t)
(register-definition-prefixes "legalese" '("legalese-"))


(provide 'legalese-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/know-your-http-well-20240726.1649/know-your-http-well-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'http-header "http-headers" "\
Display the meaning of an HTTP header

(fn HEADER)" t)
(register-definition-prefixes "http-headers" '("http-headers"))



(autoload 'http-method "http-methods" "\
Display the meaning of an HTTP method

(fn METHOD)" t)
(register-definition-prefixes "http-methods" '("http-methods"))



(autoload 'http-relation "http-relations" "\
Display the meaning of an HTTP relation

(fn RELATION)" t)
(register-definition-prefixes "http-relations" '("http-relations"))



(autoload 'http-status-code "http-status-codes" "\
Display the meaning of an HTTP status code or phrase

(fn STATUS)" t)
(register-definition-prefixes "http-status-codes" '("http-status"))



(autoload 'media-type "media-types" "\
Display the template of a media-type

(fn MEDIA-TYPE)" t)
(register-definition-prefixes "media-types" '("media-types"))


(provide 'know-your-http-well-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/compat-31.1.0.0/compat-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(register-definition-prefixes "compat" '("compat-"))



(register-definition-prefixes "compat-macs" '("compat-"))


(provide 'compat-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/kkp-20260706.858/kkp-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'kkp-disable-in-terminal "kkp" "\
Disable in this terminal where command is executed, the activated enhancements." t)
(defvar global-kkp-mode nil "\
Non-nil if Global Kkp mode is enabled.
See the `global-kkp-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-kkp-mode'.")
(custom-autoload 'global-kkp-mode "kkp" nil)
(autoload 'global-kkp-mode "kkp" "\
Toggle KKP support in all terminal frames.

This is a global minor mode.  If called interactively, toggle the
`Global Kkp mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='global-kkp-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'kkp-status "kkp" "\
Message, if terminal supports KKP, if yes, currently enabled enhancements." t)
(register-definition-prefixes "kkp" '("kkp-"))



(autoload 'kkp-debug-describe-key-translation-chain "kkp-debug" "\
Display the key translation chain for a terminal key sequence.
The translation process is performed in the following stages:
  1. Input decoding via `input-decode-map` (with fallback to KKP if needed).
  2. Normal binding lookup: if the input-decoded sequence has a normal binding,
     then remapping via `local-function-key-map` is skipped.
  3. If no normal binding is found, remap via `local-function-key-map`.
  4. Finally, `key-translation-map` is applied unconditionally.
The resulting key sequence and its final command binding are displayed.
Output is arranged in aligned columns for clarity." t)
(autoload 'kkp-debug-show-terminal-state "kkp-debug" "\
Display KKP state for the selected terminal in a help buffer.
Shows both what kkp has recorded (the `kkp--state' struct) and what the
terminal reports live, which is useful for spotting a desync between the
two (e.g. while a `kkp-with-legacy-keys' region is active, or if an
intermediary stripped the protocol).

Use `kkp-debug-show-all-terminal-states' for an overview of every
terminal." t)
(autoload 'kkp-debug-show-all-terminal-states "kkp-debug" "\
Display the KKP state of every live terminal in a help buffer.
The selected terminal is also queried live (as in
`kkp-debug-show-terminal-state'); the others show only kkp's recorded
`kkp--state', since a terminal that is not focused cannot be queried
reliably." t)
(register-definition-prefixes "kkp-debug" '("kkp-debug--"))


(provide 'kkp-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/just-mode-20250828.1824/just-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'just-mode "just-mode" "\
Major mode for editing standard Justfiles.

(fn)" t)
(add-to-list 'auto-mode-alist '("/\\(?:\\.\\)?[jJ][uU][sS][tT][fF][iI][lL][eE]\\'" . just-mode))
(register-definition-prefixes "just-mode" '("just-"))


(provide 'just-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/indent-bars-1.0.1/indent-bars-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'indent-bars-mode "indent-bars" "\
Indicate indentation with configurable bars.

This is a minor mode.  If called interactively, toggle the `Indent-Bars
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `indent-bars-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "indent-bars" '("indent-bars-"))



(autoload 'indent-bars--ts-mode "indent-bars-ts" "\
Minor mode for indent-bars using treesitter.

This is a minor mode.  If called interactively, toggle the
`Indent-Bars--Ts mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `indent-bars--ts-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "indent-bars-ts" '("indent-bars-"))


(provide 'indent-bars-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/httprepl-20141101.1734/httprepl-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'httprepl "httprepl" "\
Interactively evaluate HTTP requests at a REPL-like
interface. Switches to the buffer specified by
`httprepl-buffer-name', or creates it if it does not exist. See
`httprepl-mode' for a reference on constructing requests." t)
(register-definition-prefixes "httprepl" '("httprepl-"))


(provide 'httprepl-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/groovy-mode-20230318.533/groovy-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'groovy-electric-mode "groovy-electric" "\
Toggle Groovy Electric minor mode.

With no argument, this command toggles the mode.  Non-null prefix
argument turns on the mode.  Null prefix argument turns off the
mode.

When Groovy Electric mode is enabled, simple, double and back
quotes as well as braces are paired auto-magically. Expansion
does not occur inside comments and strings. Note that you must
have Font Lock enabled. ${ } is expanded when in a GString

This is a minor mode.  If called interactively, toggle the
`Groovy-Electric mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `groovy-electric-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "groovy-electric" '("groovy-electric-"))



(add-to-list 'auto-mode-alist '("\\.g\\(?:ant\\|roovy\\|radle\\)\\'" . groovy-mode))
(add-to-list 'auto-mode-alist '("/Jenkinsfile\\'" . groovy-mode))
(add-to-list 'interpreter-mode-alist '("groovy" . groovy-mode))
(autoload 'groovy-mode "groovy-mode" "\
Major mode for editing Groovy code.

The hook `groovy-mode-hook' is run with no args at mode
initialization.

Key bindings:
\\{groovy-mode-map}

(fn)" t)
(register-definition-prefixes "groovy-mode" '("groovy-"))



(autoload 'inf-groovy-keys "inf-groovy" "\
Set local key defs for inf-groovy in `groovy-mode'.")
(autoload 'inferior-groovy-mode "inf-groovy" "\
Major mode for interacting with an inferior groovy (groovysh) process.

The following commands are available:
\\{inferior-groovy-mode-map}

A groovy process can be fired up with \\[run-groovy].

Customisation: Entry to this mode runs the hooks on
`comint-mode-hook' and `inferior-groovy-mode-hook' (in that order).

You can send text to the inferior groovy process from other buffers containing
Groovy source.
    `switch-to-groovy' switches the current buffer to the groovy process buffer.
    `groovy-send-definition' sends the current definition to the groovy process.
    `groovy-send-region' sends the current region to the groovy process.

    `groovy-send-definition-and-go', `groovy-send-region-and-go',
        switch to the groovy process buffer after sending their text.
For information on running multiple processes in multiple buffers, see
documentation for variable `groovy-buffer'.

Commands:
Return after the end of the process' output sends the text from the
    end of process to point.
Return before the end of the process' output copies the sexp ending at point
    to the end of the process' output, and sends it.
Delete converts tabs to spaces as it moves back.
Tab indents for groovy; with argument, shifts rest
    of expression rigidly with the current line.
\\<groovy-mode-map>
\\[prog-indent-sexp] does Tab on each line starting within following expression.
Paragraphs are separated only by blank lines.  # start comments.
If you accidentally suspend your process, use \\[comint-continue-subjob]
to continue it." t)
(autoload 'run-groovy "inf-groovy" "\
Run an inferior Groovy process, input and output via buffer *groovy*.
If there is a process already running in *groovy*, switch to that buffer.
With a prefix argument, prompt for the groovysh path and arguments
(see variables `groovysh' and `groovysh-args' for the defaults).

Runs the hook `inferior-groovy-mode-hook' (after the
`comint-mode-hook' is run).  Type \\[describe-mode] in the
process buffer for a list of commands.

(fn CMD)" t)
(eval-after-load 'groovy-mode (lambda nil (add-hook 'groovy-mode-hook 'inf-groovy-keys)))
(register-definition-prefixes "inf-groovy" '("groovy" "inf" "remove-in-string" "switch-to-groovy"))


(provide 'groovy-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/graphviz-dot-mode-20250925.1226/graphviz-dot-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(register-definition-prefixes "graphviz-dot-flycheck" '("graphviz-dot--"))



(autoload 'graphviz-dot-mode "graphviz-dot-mode" "\
Major mode for the dot language.

Functionality specific to this mode:

  `indent-for-tab-command'    \\[indent-for-tab-command]
        Indents a single line.
  `graphviz-dot-preview'      \\[graphviz-dot-preview]
        Previews graph in a buffer.
  `graphviz-dot-view'         \\[graphviz-dot-view]
        Views graph in an external viewer.
  `graphviz-dot-indent-line'  \\[graphviz-dot-indent-line]
        Indents current line of code.

Variables specific to this mode:

  `graphviz-dot-dot-program'                   (default `dot')
       Program used to compile the graphs.
  `graphviz-dot-preview-extension'             (default `png')
       File type to use for output.
  `graphviz-dot-view-command'                  (default `dotty %s')
       Command to run when `graphviz-dot-view' is executed.
  `graphviz-dot-view-edit-command'             (default nil)
       If the user should be asked to edit the view command.
  `graphviz-dot-save-before-view'              (default t)
       Automatically save current buffer berore `graphviz-dot-view'.

(fn)" t)
(autoload 'graphviz-dot-preview "graphviz-dot-mode" "\
Compile the graph between BEGIN and END and preview it in an other buffer.
BEGIN (resp. END) is a number defaulting to `point-min' (resp. `point-max')
representing the current buffer's point where the graph definition starts
(resp. stops).

(fn &optional BEGIN END)" t)
(autoload 'graphviz-turn-on-live-preview "graphviz-dot-mode" "\
Turn on live preview.
This will update the preview on every save." t)
(autoload 'graphviz-turn-off-live-preview "graphviz-dot-mode" "\
Turn off live preview.
Saving the file will no longer also update the preview." t)
(add-to-list 'auto-mode-alist '("\\.dot\\'" . graphviz-dot-mode))
(add-to-list 'auto-mode-alist '("\\.gv\\'" . graphviz-dot-mode))
(register-definition-prefixes "graphviz-dot-mode" '("dot-menu" "graphviz-"))


(provide 'graphviz-dot-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/dumb-jump-20250822.2314/dumb-jump-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(defvar dumb-jump-mode-map (let ((map (make-sparse-keymap))) (define-key map (kbd "C-M-g") 'dumb-jump-go) (define-key map (kbd "C-M-p") 'dumb-jump-back) (define-key map (kbd "C-M-q") 'dumb-jump-quick-look) map))
(autoload 'dumb-jump-back "dumb-jump" "\
Jump back to where the last jump was done." t)
(autoload 'dumb-jump-quick-look "dumb-jump" "\
Run dumb-jump-go in quick look mode.  That is, show a tooltip of where it would jump instead." t)
(autoload 'dumb-jump-go-other-window "dumb-jump" "\
Like 'dumb-jump-go' but use 'find-file-other-window' instead of 'find-file'." t)
(autoload 'dumb-jump-go-current-window "dumb-jump" "\
Like dumb-jump-go but always use 'find-file'." t)
(autoload 'dumb-jump-go-prefer-external "dumb-jump" "\
Like dumb-jump-go but prefer external matches from the current file." t)
(autoload 'dumb-jump-go-prompt "dumb-jump" "\
Like dumb-jump-go but prompts for function instead of using under point" t)
(autoload 'dumb-jump-go-prefer-external-other-window "dumb-jump" "\
Like dumb-jump-go-prefer-external but use 'find-file-other-window' instead of 'find-file'." t)
(autoload 'dumb-jump-go "dumb-jump" "\
Go to the function/variable declaration for thing at point.
When USE-TOOLTIP is t a tooltip jump preview will show instead.
When PREFER-EXTERNAL is t it will sort external matches before
current file.

(fn &optional USE-TOOLTIP PREFER-EXTERNAL PROMPT)" t)
(defvar dumb-jump-mode nil "\
Non-nil if Dumb-Jump mode is enabled.
See the `dumb-jump-mode' command
for a description of this minor mode.")
(custom-autoload 'dumb-jump-mode "dumb-jump" nil)
(autoload 'dumb-jump-mode "dumb-jump" "\
Minor mode for jumping to variable and function definitions

This is a global minor mode.  If called interactively, toggle the
`Dumb-Jump mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='dumb-jump-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'dumb-jump-xref-activate "dumb-jump" "\
Function to activate xref backend.
Add this function to `xref-backend-functions' to dumb jump to be
activiated, whenever it finds a project. It is recommended to add
it to the end, so that it only gets activated when no better
option is found.")
(register-definition-prefixes "dumb-jump" '("dumb-jump-"))


(provide 'dumb-jump-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/corfu-20250923.1250/corfu-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'corfu-mode "corfu" "\
COmpletion in Region FUnction.

This is a minor mode.  If called interactively, toggle the `Corfu mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `corfu-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-corfu-mode 'globalized-minor-mode t)
(defvar global-corfu-mode nil "\
Non-nil if Global Corfu mode is enabled.
See the `global-corfu-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-corfu-mode'.")
(custom-autoload 'global-corfu-mode "corfu" nil)
(autoload 'global-corfu-mode "corfu" "\
Toggle Corfu mode in all buffers.
With prefix ARG, enable Global Corfu mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Corfu mode is enabled in all buffers where `corfu--on' would do it.

See `corfu-mode' for more information on Corfu mode.

`global-corfu-modes' is used to control which modes this minor mode is
used in.

(fn &optional ARG)" t)
(defvar global-corfu-modes t "\
Which major modes `corfu-mode' is switched on in.
This variable can be either t (all major modes), nil (no major modes),
or a list of modes and (not modes) to switch use this minor mode or
not.  For instance

  (c-mode (not message-mode mail-mode) text-mode)

means \"use this mode in all modes derived from `c-mode', don't use in
modes derived from `message-mode' or `mail-mode', but do use in other
modes derived from `text-mode'\".  An element with value t means \"use\"
and nil means \"don't use\".  There's an implicit nil at the end of the
list.")
(custom-autoload 'global-corfu-modes "corfu" t)
(register-definition-prefixes "corfu" '("corfu-" "global-corfu-minibuffer"))



(defvar corfu-echo-mode nil "\
Non-nil if Corfu-Echo mode is enabled.
See the `corfu-echo-mode' command
for a description of this minor mode.")
(custom-autoload 'corfu-echo-mode "corfu-echo" nil)
(autoload 'corfu-echo-mode "corfu-echo" "\
Show candidate documentation in echo area.

This is a global minor mode.  If called interactively, toggle the
`Corfu-Echo mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='corfu-echo-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-echo" '("corfu-echo-"))



(defvar corfu-history-mode nil "\
Non-nil if Corfu-History mode is enabled.
See the `corfu-history-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `corfu-history-mode'.")
(custom-autoload 'corfu-history-mode "corfu-history" nil)
(autoload 'corfu-history-mode "corfu-history" "\
Update Corfu history and sort completions by history.

This is a global minor mode.  If called interactively, toggle the
`Corfu-History mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='corfu-history-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-history" '("corfu-history"))



(defvar corfu-indexed-mode nil "\
Non-nil if Corfu-Indexed mode is enabled.
See the `corfu-indexed-mode' command
for a description of this minor mode.")
(custom-autoload 'corfu-indexed-mode "corfu-indexed" nil)
(autoload 'corfu-indexed-mode "corfu-indexed" "\
Prefix candidates with indices.

This is a global minor mode.  If called interactively, toggle the
`Corfu-Indexed mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='corfu-indexed-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-indexed" '("corfu-indexed-"))



(autoload 'corfu-info-documentation "corfu-info" "\
Show documentation of current candidate.
If called with a prefix ARG, the buffer is persistent.

(fn &optional ARG)" t)
(autoload 'corfu-info-location "corfu-info" "\
Show location of current candidate.
If called with a prefix ARG, the buffer is persistent.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-info" '("corfu-info--"))



(defvar corfu-popupinfo-mode nil "\
Non-nil if Corfu-Popupinfo mode is enabled.
See the `corfu-popupinfo-mode' command
for a description of this minor mode.")
(custom-autoload 'corfu-popupinfo-mode "corfu-popupinfo" nil)
(autoload 'corfu-popupinfo-mode "corfu-popupinfo" "\
Corfu info popup minor mode.

This is a global minor mode.  If called interactively, toggle the
`Corfu-Popupinfo mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='corfu-popupinfo-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-popupinfo" '("corfu-popupinfo-"))



(autoload 'corfu-quick-jump "corfu-quick" "\
Jump to candidate using quick keys." t)
(autoload 'corfu-quick-insert "corfu-quick" "\
Insert candidate using quick keys." t)
(autoload 'corfu-quick-complete "corfu-quick" "\
Complete candidate using quick keys." t)
(register-definition-prefixes "corfu-quick" '("corfu-quick"))


(provide 'corfu-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/corfu-terminal-0.7/corfu-terminal-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(defvar corfu-terminal-mode nil "\
Non-nil if Corfu-Terminal mode is enabled.
See the `corfu-terminal-mode' command
for a description of this minor mode.")
(custom-autoload 'corfu-terminal-mode "corfu-terminal" nil)
(autoload 'corfu-terminal-mode "corfu-terminal" "\
Corfu popup on terminal.

This is a global minor mode.  If called interactively, toggle the
`Corfu-Terminal mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='corfu-terminal-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "corfu-terminal" '("corfu-terminal-"))


(provide 'corfu-terminal-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/colorful-mode-1.2.5/colorful-mode-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'colorful-mode "colorful-mode" "\
Preview any color in your buffer such as hex, color names, CSS rgb in real time.

This is a minor mode.  If called interactively, toggle the `Colorful
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `colorful-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'turn-on-colorful-mode "colorful-mode" "\
Turn on `colorful-mode' mode in the current buffer.")
(put 'global-colorful-mode 'globalized-minor-mode t)
(defvar global-colorful-mode nil "\
Non-nil if Global Colorful mode is enabled.
See the `global-colorful-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-colorful-mode'.")
(custom-autoload 'global-colorful-mode "colorful-mode" nil)
(autoload 'global-colorful-mode "colorful-mode" "\
Toggle Colorful mode in all buffers.
With prefix ARG, enable Global Colorful mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Colorful mode is enabled in all buffers where `turn-on-colorful-mode'
would do it.

See `colorful-mode' for more information on Colorful mode.

`global-colorful-modes' is used to control which modes this minor mode
is used in.

(fn &optional ARG)" t)
(defvar global-colorful-modes '(prog-mode help-mode html-mode css-mode latex-mode) "\
Which major modes `colorful-mode' is switched on in.
This variable can be either t (all major modes), nil (no major modes),
or a list of modes and (not modes) to switch use this minor mode or
not.  For instance

  (c-mode (not message-mode mail-mode) text-mode)

means \"use this mode in all modes derived from `c-mode', don't use in
modes derived from `message-mode' or `mail-mode', but do use in other
modes derived from `text-mode'\".  An element with value t means \"use\"
and nil means \"don't use\".  There's an implicit nil at the end of the
list.")
(custom-autoload 'global-colorful-modes "colorful-mode" t)
(register-definition-prefixes "colorful-mode" '("colorful-"))


(provide 'colorful-mode-autoloads)


)
(let* ((load-file-name "/Users/stpierre/.emacs.d/elpa/cape-20260905.500/cape-autoloads.el")(load-true-file-name load-file-name))



(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))




(autoload 'cape-history "cape" "\
Complete from Eshell, Comint or minibuffer history.
See also `consult-history' for a more flexible variant based on
`completing-read'.  If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-file "cape" "\
Complete file name at point.
See the user option `cape-file-directory-must-exist'.
If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-elisp-symbol "cape" "\
Complete Elisp symbol at point.
If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-elisp-block "cape" "\
Complete Elisp in Org or Markdown code block.
This Capf is particularly useful for literate Emacs configurations.
If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-dabbrev "cape" "\
Complete with Dabbrev at point.

If INTERACTIVE is nil the function acts like a Capf.  In case you
observe a performance issue with auto-completion and `cape-dabbrev'
it is strongly recommended to disable scanning in other buffers.
See the user option `cape-dabbrev-buffer-function'.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-dict "cape" "\
Complete word from dictionary at point.
This completion function works best if the dictionary is sorted
by frequency.  See the custom option `cape-dict-file'.  If
INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-abbrev "cape" "\
Complete abbreviation at point.
If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-line "cape" "\
Complete current line from other lines.
The buffers returned by `cape-line-buffer-function' are scanned for lines.
If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)
(autoload 'cape-company-to-capf "cape" "\
Convert Company BACKEND function to Capf.
VALID is a function taking the old and new input string.  It should
return nil if the cached candidates became invalid.  The default value
for VALID is `string-prefix-p' such that the candidates are only fetched
again if the input prefix changed.

(fn BACKEND &optional VALID)")
(autoload 'cape-interactive "cape" "\
Complete interactively with the given CAPFS.

(fn &rest CAPFS)")
(autoload 'cape-capf-interactive "cape" "\
Create interactive completion function from CAPF.

(fn CAPF)")
(autoload 'cape-wrap-super "cape" "\
Call CAPFS and return merged completion result.
The CAPFS list can contain the keyword `:with' to mark the Capfs
afterwards as auxiliary.  One of the non-auxiliary Capfs before `:with'
must return non-nil for the super Capf to set in and return a non-nil
result.  Such behavior is useful when listing multiple super Capfs in
the `completion-at-point-functions':

  (setq completion-at-point-functions
        (list (cape-capf-super \\='elisp-completion-at-point
                               :with \\='tempel-complete)
              (cape-capf-super \\='cape-dabbrev
                               :with \\='tempel-complete)))

See the dual `cape-wrap-choose' if you want to try multiple Capfs in
turn.

(fn &rest CAPFS)")
(autoload 'cape-wrap-choose "cape" "\
Call each of CAPFS in turn and return first non-nil result.
Use `cape-wrap-choose' to create a single Capf from multiple Capfs.
Usually you want to add multiple non-exclusive Capfs to the variable
`completion-at-point-functions' directly instead.  See the dual
`cape-wrap-super' if you want to merge multiple Capf results.

(fn &rest CAPFS)")
(autoload 'cape-wrap-debug "cape" "\
Call CAPF and return a completion table which prints trace messages.
If CAPF is an anonymous lambda, pass the Capf NAME explicitly for
meaningful debugging output.

(fn CAPF &optional NAME)")
(autoload 'cape-wrap-buster "cape" "\
Call CAPF and return a completion table with cache busting.
This function can be used as an advice around an existing Capf.
The cache is busted when the input changes.  The argument VALID
can be a function taking the old and new input string.  It should
return nil if the new input requires that the completion table is
refreshed.  The default value for VALID is `equal', such that the
completion table is refreshed on every input change.

(fn CAPF &optional VALID)")
(autoload 'cape-wrap-passthrough "cape" "\
Call CAPF and make sure that no completion style filtering takes place.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-properties "cape" "\
Call CAPF and add completion PROPERTIES.
Completion properties include :exclusive, :category,
:annotation-function, :affixation-function, :display-sort-function,
:company-kind, :company-doc-buffer, :company-docsig, :company-location,
:company-deprecated and :company-prefix-length.

(fn CAPF &rest PROPERTIES)")
(autoload 'cape-wrap-nonexclusive "cape" "\
Call CAPF and ensure that it is marked as non-exclusive.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-sort "cape" "\
Call CAPF and add SORT function as completion metadata.
If the SORT argument is nil or not given, the completion UI will use
its own default sorting algorithm.  This function can be used as an
advice around an existing Capf.

(fn CAPF &optional SORT)")
(autoload 'cape-wrap-predicate "cape" "\
Call CAPF and add an additional candidate PREDICATE.
The PREDICATE is passed the candidate symbol or string.

(fn CAPF PREDICATE)")
(autoload 'cape-wrap-silent "cape" "\
Call CAPF and silence it (no messages, no errors).
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-case-fold "cape" "\
Call CAPF and return a case-insensitive completion table.
If NOFOLD is non-nil return a case sensitive table instead.  This
function can be used as an advice around an existing Capf.

(fn CAPF &optional NOFOLD)")
(autoload 'cape-wrap-noninterruptible "cape" "\
Call CAPF and return a non-interruptible completion table.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-prefix-length "cape" "\
Call CAPF and ensure that prefix length is greater or equal than LENGTH.
If the prefix is long enough, enforce auto completion.

(fn CAPF LENGTH)")
(autoload 'cape-wrap-inside-faces "cape" "\
Call CAPF only if inside FACES.

(fn CAPF &rest FACES)")
(autoload 'cape-wrap-inside-code "cape" "\
Call CAPF only if inside code, not inside a comment or string.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-inside-comment "cape" "\
Call CAPF only if inside comment.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-inside-string "cape" "\
Call CAPF only if inside string.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-accept-all "cape" "\
Call CAPF and return a completion table which accepts every input.
This function can be used as an advice around an existing Capf.

(fn CAPF)")
(autoload 'cape-wrap-trigger "cape" "\
Ensure that TRIGGER character occurs before point and then call CAPF.
See also `corfu-auto-trigger'.
Example:
  (setq corfu-auto-trigger \"/\"
        completion-at-point-functions
        (list (cape-capf-trigger \\='cape-abbrev ?/)))

(fn CAPF TRIGGER)")
 (autoload 'cape-capf-accept-all "cape")
 (autoload 'cape-capf-buster "cape")
 (autoload 'cape-capf-case-fold "cape")
 (autoload 'cape-capf-choose "cape")
 (autoload 'cape-capf-debug "cape")
 (autoload 'cape-capf-inside-code "cape")
 (autoload 'cape-capf-inside-comment "cape")
 (autoload 'cape-capf-inside-faces "cape")
 (autoload 'cape-capf-inside-string "cape")
 (autoload 'cape-capf-nonexclusive "cape")
 (autoload 'cape-capf-noninterruptible "cape")
 (autoload 'cape-capf-passthrough "cape")
 (autoload 'cape-capf-predicate "cape")
 (autoload 'cape-capf-prefix-length "cape")
 (autoload 'cape-capf-properties "cape")
 (autoload 'cape-capf-silent "cape")
 (autoload 'cape-capf-sort "cape")
 (autoload 'cape-capf-super "cape")
 (autoload 'cape-capf-trigger "cape")
 (autoload 'cape-prefix-map "cape" nil t 'keymap)
(register-definition-prefixes "cape" '("cape-"))



 (autoload 'cape-tex "cape-char" nil t)
 (autoload 'cape-sgml "cape-char" nil t)
 (autoload 'cape-rfc1345 "cape-char" nil t)
 (autoload 'cape-emoji "cape-char" nil t)
(register-definition-prefixes "cape-char" '("cape-char--"))



(autoload 'cape-keyword "cape-keyword" "\
Complete programming language keyword at point.
See the variable `cape-keyword-list'.
If INTERACTIVE is nil the function acts like a capf.

(fn &optional INTERACTIVE)" t)
(register-definition-prefixes "cape-keyword" '("cape-"))


(provide 'cape-autoloads)


)
(defvar package-activated-list)
(setq package-activated-list
      (delete-dups
       (append
	'(ws-butler treesit-auto hcl-mode dash terraform-mode
		    reformatter sqlformat solarized-theme scratch s
		    protobuf-mode popup popon markdown-mode legalese
		    know-your-http-well compat kkp just-mode
		    indent-bars httprepl groovy-mode graphviz-dot-mode
		    dumb-jump corfu corfu-terminal colorful-mode cape)
	package-activated-list)))
(progn
  (require 'info) (info-initialize)
  (setq Info-directory-list
	(append
	 '("/Users/stpierre/.emacs.d/elpa/compat-31.1.0.0"
	   "/Users/stpierre/.emacs.d/elpa/dash-20250312.1307")
	 Info-directory-list)))

;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; byte-compile-warnings: (not make-local)
;; End:
